# Generated by Django 3.2.9 on 2021-11-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Libro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
